### ISSUE TITLE
What do these Error Messages Mean? 

### ISSUE THREAD

**Issue by JohnR123** [Bodmer/TFT_HX8357_Due#7]
Please see the attached file. I am getting these error messages when I try to complie any sketch using the TFT_HX8357B. I do not know what the problem may be. Could you please help in interpreting and how I can fix so that it works. I am using the examples and library on github.

[Weather Sta Error Msgs 110618.txt](https://github.com/Bodmer/TFT_HX8357_Due/files/2555987/Weather.Sta.Error.Msgs.110618.txt)

**Comment by Bodmer** [comment]
It looks like you have not selected the right board in the IDE. Are you using an [Arduino Due](https://store.arduino.cc/arduino-due)?

**Comment by Bodmer** [comment]
It looks like you are trying to compile an example called Wireless_Weather_Station which library does that come from?

**Comment by JohnR123** [comment]
Bodmer - Thank you for the reply. I am using the Arduino Due. Originally, I was trying to build the wireless weather station project as described here:

 http://educ8s.tv/arduino-wireless-weather-station/

But I ran into problems compiling the code for the receiver end that has the TFT display. So i thought i would take a step back and just try to compile one of the examples in your library and get the TFT working that way first before moving back up. But it appears that I may have something mixed up with the libraries, or in a library. I just can't readily tell from the error messages where the problem is. Do I have something referenced wrong somewhere? Thank you for your help.

**Comment by Bodmer** [comment]
You have the wrong board selected in the Arduino IDE, the board selected must be:
**Arduino Due (Programming Port)**
In the tools>board menu.

You have selected the Arduino **Duemilanove or Diecimila** which is a completely different board which the library does not support.

**Comment by JohnR123** [comment]
Bodmer - Thank you for your help!! I should have read the Due getting started section on the Arduino web site. Had to uninstall and then reinstall the IDE to get the driver to install per the getting started example, but then I could compile and load the examples in your library without any problems. Again,  thank you for your help in pointing out a basic step that I should have seen.

**Comment by Bodmer** [comment]
No problem, glad to hear it is working for you now.
