### ISSUE TITLE
TFT LCD display part links broken

### ISSUE THREAD

**Issue by Erik-Koning** [Bodmer/TFT_HX8357_Due#9]
Hello,

Awesome library!
Could you advise/update the list of 16bit display parts that will work with this library?
The links youve posted in the readme to LCD panels are no longer active.

**Comment by Bodmer** [comment]
Go for an [ILI9481 board like this](https://www.aliexpress.com/item/32832537687.html?spm=a2g0o.productlist.0.0.596fce10N3BQSV&algo_pvid=90b855b4-4c07-41ab-92b3-2e86352fc04c&algo_expid=90b855b4-4c07-41ab-92b3-2e86352fc04c-19&btsid=0b0a01f816037632724616851e92ee&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_).
